HospitalManagement/HospitalA/urls.py
from django.urls import path
from . import views

app_name = 'HospitalA'

urlpatterns = [
    path('', views.index, name='index'),

    # Admin URLs
    path('hospital_admin/login/', views.AdminLoginView.as_view(), name='admin-login'),
    path('hospital_admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),

    # Doctor URLs
    path('hospital_admin/register_doctor/', views.register_doctor, name='register-doctor'),
    path('doctor/login/', views.DoctorLoginView.as_view(), name='doctor-login'),
    path('doctor/dashboard/', views.doctor_dashboard, name='doctor_dashboard'),

    # Patient URLs
    path('doctor/register_patient/', views.register_patient, name='register-patient'),
    path('patient/login/', views.PatientLoginView.as_view(), name='patient-login'),
    path('patient/dashboard/', views.patient_dashboard, name='patient_dashboard'),
]

HospitalManagement/HospitalManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('HospitalA/', include('HospitalA.urls')),
    path('', include('HospitalA.urls')),
]

HospitalManagement/HospitalA/models.py
from django.db import models
import uuid
from django.utils import timezone
from django.contrib.auth.models import AbstractUser, Group, Permission

class Admin(models.Model):
    username = models.CharField(max_length=50, default='root', unique=True)
    password = models.CharField(max_length=255, default='root@123')

class Doctor(AbstractUser):
    license_number = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=100)
    mobile_number = models.CharField(max_length=15)
    email = models.EmailField()
    username = models.CharField(max_length=30, unique=False, default="Doctor")
    first_name = models.CharField(max_length=30, default="Hospital")
    last_name = models.CharField(max_length=30, default="A")
    is_staff = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=True)
    backend = models.CharField(max_length=255, default='HospitalA.backends.DoctorBackend')
            

    groups = models.ManyToManyField(Group, related_name='doctor_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='doctor_user_permissions')

class Patient(AbstractUser):
    unique_code = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    allergies = models.TextField()
    mobile_number = models.CharField(max_length=15)
    email = models.EmailField(default="patient@gmail.com")
    emergency_contact = models.CharField(max_length=15)
    chronic_disease = models.CharField(max_length=100, blank=True, null=True)  # Changed to CharField
    username = models.CharField(max_length=30, unique=False, default="Patient")
    first_name = models.CharField(max_length=30, default="Patient")
    last_name = models.CharField(max_length=30, default="Panvel")
    backend = models.CharField(max_length=255, default='HospitalA.backends.PatientBackend')

    groups = models.ManyToManyField(Group, related_name='patient_groups')
    user_permissions = models.ManyToManyField(Permission, related_name='patient_user_permissions')

from django.contrib.auth import get_user_model

class LoginLog(models.Model):
    user_type = models.CharField(max_length=10, default=Doctor)  # Add a field to distinguish between 'Doctor' and 'Patient'
    user_id = models.PositiveIntegerField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user_type} - {self.user_id} - {self.timestamp}"


HospitalManagement/HospitalA/forms.py
from django import forms
from .models import Doctor, Patient

class AdminLoginForm(forms.Form):
    username = forms.CharField(max_length=50, initial='root')  # Set default username
    password = forms.CharField(widget=forms.PasswordInput, initial='root@123')  # Set default password

class DoctorRegistrationForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['license_number', 'name', 'mobile_number', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

class DoctorLoginForm(forms.Form):
    license_number = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)

class PatientRegistrationForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['name', 'age', 'allergies', 'mobile_number', 'emergency_contact', 'chronic_disease', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

class PatientLoginForm(forms.Form):
    unique_code = forms.UUIDField()
    password = forms.CharField(widget=forms.PasswordInput)

HospitalManagement/HospitalA/views.py
from django.shortcuts import render, redirect
from .backends import DoctorBackend, PatientBackend
from django.contrib.auth import login, authenticate
from django.views import View
from django.contrib import messages
from .forms import AdminLoginForm, DoctorRegistrationForm, DoctorLoginForm, PatientRegistrationForm, PatientLoginForm
from .models import Doctor, Patient
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import BACKEND_SESSION_KEY
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test


def index(request):
    # Your logic for the doctor dashboard goes here
    return render(request, 'index.html')

class AdminLoginView(View):
    template_name = 'admin_login.html'
    form_class = AdminLoginForm

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            # Hardcoded username and password for demonstration
            expected_username = 'root'
            expected_password = 'root@123'

            entered_username = form.cleaned_data['username']
            entered_password = form.cleaned_data['password']

            # Check if the user with the given username exists
            user = User.objects.filter(username=expected_username).first()

            if user:
                # If the user exists, check the password and log in
                if user.check_password(expected_password):
                    login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                    messages.success(request, 'Successfully logged in as admin.')
                    return redirect('HospitalA:admin_dashboard')
                else:
                    messages.error(request, 'Invalid login credentials.')
            else:
                # If the user does not exist, create a new user and log in
                user = User.objects.create_user(username=expected_username, password=expected_password)
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                messages.success(request, 'Successfully logged in as admin.')
                return redirect('HospitalA:admin_dashboard')

        return render(request, self.template_name, {'form': form})

#Admin Dashboard

@login_required(login_url='/hospital_admin/login/')
def admin_dashboard(request):
    # Your logic for admin dashboard goes here
    return render(request, 'admin_dashboard.html')

#Doctor

@login_required(login_url='/hospital_admin/login/')
def register_doctor(request):
    if request.method == 'POST':
        form = DoctorRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Doctor registered successfully!')
            return redirect('HospitalA:admin_dashboard')
    else:
        form = DoctorRegistrationForm()

    return render(request, 'register_doctor.html', {'form': form})

class DoctorLoginView(View):
    template_name = 'doctor_login.html'
    form_class = DoctorLoginForm

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            license_number = form.cleaned_data['license_number']
            password = form.cleaned_data['password']

            user = DoctorBackend().authenticate(request, license_number=license_number, password=password)

            if user is not None:
                login(request, user, backend = 'HospitalA.backends.DoctorBackend')
                messages.success(request, 'Successfully logged in as doctor.')
                return redirect('HospitalA:doctor_dashboard')
            else:
                messages.error(request, 'Invalid login credentials.')

        return render(request, self.template_name, {'form': form})


@user_passes_test(lambda u: u.is_authenticated == False, login_url='/doctor/login/')
def doctor_dashboard(request):
    
    return render(request, 'doctor_dashboard.html')

#Patient

@user_passes_test(lambda u: u.is_authenticated == False, login_url='/doctor/login/')
def register_patient(request):
    if request.method == 'POST':
        form = PatientRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Patient registered successfully!')
            return redirect('HospitalA:doctor_dashboard')  # Redirect to doctor dashboard after patient registration
    else:
        form = PatientRegistrationForm()

    return render(request, 'register_patient.html', {'form': form})

class PatientLoginView(View):
    template_name = 'patient_login.html'
    form_class = PatientLoginForm

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            unique_code = form.cleaned_data['unique_code']
            password = form.cleaned_data['password']

            user = PatientBackend().authenticate(request, unique_code=unique_code, password=password)

            if user is not None:
                login(request, user, backend = 'HospitalA.backends.PatientBackend')
                messages.success(request, 'Successfully logged in as patient.')
                return redirect('HospitalA:patient_dashboard')
            else:
                messages.error(request, 'Invalid login credentials.')

        return render(request, self.template_name, {'form': form})


@user_passes_test(lambda u: u.is_authenticated == False, login_url='/patient/login/')
def patient_dashboard(request):
    # Your logic for the doctor dashboard goes here
    return render(request, 'patient_dashboard.html')

HospitalManagement/HospitalA/templates/admin_dashboard.html
<!-- admin_dashboard.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
</head>
<body>

    <h1>Welcome to the Admin Dashboard</h1>

    <!-- Display dynamic content or information here -->

    <a href="{% url 'HospitalA:register-doctor' %}">Register Doctor</a>

    <!-- Add more HTML content as needed -->

</body>
</html>

HospitalManagement/HospitalA/templates/admin_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
</head>
<body>

    <h1>Admin Login</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

    <!-- Add more HTML content as needed -->

</body>
</html>

HospitalManagement/HospitalA/templates/doctor_dashboard.html
<!-- doctor_dashboard.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doctor Dashboard</title>
</head>
<body>

    <h1>Welcome to the Doctor Dashboard</h1>

    <!-- Display dynamic content or information here -->

    <a href="{% url 'HospitalA:register-patient' %}">Register Patient</a>

    <!-- Add more HTML content as needed -->

</body>
</html>

HospitalManagement/HospitalA/templates/doctor_login.html
<!-- doctor_login.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doctor Login</title>
</head>
<body>

    <h1>Doctor Login</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

    <!-- Add more HTML content as needed -->

</body>
</html>

HospitalManagement/HospitalA/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <STYle>
        .crousal{
    min-height: 400px;
}
.card{
    height: 500px;
    width: 400px;
    background-color: rgba(236, 209, 209, 0.404);
    margin: 10px;
    transition:all .9s cubic-bezier(0,1.51,.44,1.08)
}
.card:hover{
    transform: scale(1.02);
}
.card-container{
    display: flex;
    flex-wrap: wrap;
    align-content: center;
    padding: 10px 0px;
    justify-content: center;
}
footer{
    background-color: black;
    min-height: 100px;
}
    </STYle>
</head>
<body>
  {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                  </li>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
    </header>
    <main>
        <!-- crousal -->
    <div class="crousal"><div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://images.unsplash.com/file-1682622660962-5e4aae8e7b30image?dpr=2&auto=format&fit=crop&w=416&q=60" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://images.unsplash.com/file-1682622660962-5e4aae8e7b30image?dpr=2&auto=format&fit=crop&w=416&q=60" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://images.unsplash.com/file-1682622660962-5e4aae8e7b30image?dpr=2&auto=format&fit=crop&w=416&q=60" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div></div>    

    <div class="card-container">
        <div class="card">hihih</div>
        <div class="card">hihih</div>
        <div class="card">hihih</div>
        <div class="card">hihih</div>
        <div class="card">hihih</div>
    </div>


    </main>
    <footer>
        footer
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

HospitalManagement/HospitalA/templates/patient_dashboard.html
<!-- patient_dashboard.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Dashboard</title>
</head>
<body>

    <h1>Welcome to the Patient Dashboard</h1>

    <!-- Display dynamic content or information here -->

    <!-- Add more HTML content as needed -->

</body>
</html>

HospitalManagement/HospitalA/templates/patient_login.html
<!-- patient_login.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Login</title>
</head>
<body>

    <h1>Patient Login</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>

    <!-- Add more HTML content as needed -->

</body>
</html>

HospitalManagement/HospitalA/templates/register_doctor.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>loginpage</title>
    <style>
      body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background: #f5f5f7;
  }
  
  .container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    
  }
  
  .card {
    width: 300px;
    background-color: #fff;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    text-align: center;
  }
  
  h2 {
    color: #007BFF;
    margin-bottom: 20px;
  }
  
  form {
    display: flex;
    flex-direction: column;
  }
  
  label {
    text-align: left;
    margin-bottom: 5px;
  }
  
  input {
    padding: 10px;
    margin-bottom: 10px;
    border: 1px solid #ddd;
    border-radius: 5px;
  }
  
  button {
    padding: 10px;
    background-color: #007BFF;
    color: #fff;
    border: none;
    border-radius: 5px;
    cursor: pointer;
  }
  
  .switch {
    margin-top: 15px;
    font-size: 14px;
  }
  
  .switch a {
    color: #007BFF;
    text-decoration: none;
  }
  
    </style>
</head>

<body>
    <div class="container">
        <div class="card">
          <h2>Registration</h2>
          {% if messages %}
          <ul class="messages">
              {% for message in messages %}
                  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
      {% endif %}
      
          <h1>Doctor Registration</h1>
      
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form>
      
        </div>
      </div>
</body>

</html>

HospitalManagement/HospitalA/templates/register_patient.html
<!-- patient_registration.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Registration</title>
</head>
<body>

    <h1>Patient Registration</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>

    <!-- Add more HTML content as needed -->

</body>
</html>